name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: Hasona57
          filename: github-metrics.svg

          base: header, activity, repositories, metadata
          config_timezone: Africa/Cairo

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: http://waka.hackclub.com
          plugin_wakatime_user: Hasona57
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages
          plugin_wakatime_limit: 4
